Django/homework/django_orm - with - view/django_ws_5_b/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login')
]

Django/homework/django_orm - with - view/django_ws_5_b/todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('accounts/', include('accounts.urls')),
]

Django/homework/django_orm - with - view/django_ws_5_b/todos/urls.py
from django.urls import path
from . import views


app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_todo/', views.create_todo, name='create_todo'),
    path('<int:todo_pk>/', views.detail, name='detail'),
    path('new_todo/', views.new_todo, name='new_todo'),
    path('<int:todo_pk>/delete/', views.delete_todo, name='delete_todo'),
]

Django/homework/django_orm - with - view/django_ws_5_b/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    work = models.CharField(max_length=100)
    content = models.TextField()
    is_completed = models.BooleanField()
    created_at = models.DateField(auto_now_add=True)

Django/homework/django_orm - with - view/django_ws_5_b/accounts/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request, 'accounts/login.html')

Django/homework/django_orm - with - view/django_ws_5_b/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    todo_list = Todo.objects.all()
    context = {
        'todo_list': todo_list
    }
    return render(request, 'todos/index.html', context)

def create_todo(request):
    return render(request, 'todos/create_todo.html')

def detail(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    context = {
        'todo': todo
    }
    return render(request, 'todos/detail.html', context)

def new_todo(request):
    work = request.POST.get('work')
    content = request.POST.get('content')
    is_completed = False

    todo = Todo(work=work, content=content, is_completed=is_completed)
    todo.save()
    return redirect('todos:detail', todo.pk)

def delete_todo(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    todo.delete()
    return redirect('todos:index')

Django/homework/django_orm - with - view/django_ws_5_b/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
  <h1>로그인 페이지</h1>
  <form action="">
    <input type="text">
    <input type="password" name="" id="">
    <input type="submit" value="로그인">
  </form>
{% endblock content %}

Django/homework/django_orm - with - view/django_ws_5_b/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>할 일 목록 관리 프로젝트</title>
</head>
<body>
  <a href="{% url "todos:index" %}">[MAIN]</a> | 
  <a href="{% url "todos:create_todo" %}">[CREATE]</a>
  <a href="{% url "accounts:login" %}">[LOGIN]</a>
  {% block content %}
  {% endblock content %}
</body>
</html>