misc/ssafy-project/project6/ver2_movie/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:user_pk>/update/', views.update, name='update'),
    path('<int:user_pk>/delete/', views.delete, name='delete'),
    path('<int:user_pk>/password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

misc/ssafy-project/project6/ver2_movie/movies/urls.py
from django.urls import path
from .import views


app_name = "movies"

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movies_pk>/', views.detail, name='detail'),
    path('<int:movies_pk>/update/', views.update, name='update'),
    path('<int:movies_pk>/delete/', views.delete, name='delete'),
    path('<int:movies_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:movies_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:movies_pk>/likes', views.likes, name='likes'),

]

misc/ssafy-project/project6/ver2_movie/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

misc/ssafy-project/project6/ver2_movie/templates/_navbar.html
<nav class="navbar fixed-top bg-dark" data-bs-theme="dark">
  <div class="container-fluid" style='justify-content: start;'>
    <a class="navbar-brand" href="{% url "movies:index" %}">MOVIE</a>
    {% if request.user.is_authenticated %}
    <ul class="navbar-nav me-2">
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'movies:create' %}">영화 등록</a>
      </li>
    </ul>
      <ul class="navbar-nav me-2">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:update' user.pk %}">회원정보수정</a>
        </li>
      </ul>
      <ul class="navbar-nav me-2">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:profile' user.username %}">프로필</a>
        </li>
      </ul>
      <ul class="navbar-nav me-2">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:logout' %}">로그아웃</a>
        </li>
      </ul>
    {% else %}
    <ul class="navbar-nav me-2">
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'accounts:signup' %}">회원가입</a>
      </li>
    </ul>
    <ul class="navbar-nav me-2">
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">로그인</a>
      </li>
    </ul>
    {% endif %}
  </div>
</nav>

misc/ssafy-project/project6/ver2_movie/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="mt-3 container">
    <div class="mt-3 mb-4 pb-5">
      {% include '_navbar.html' %}
    </div>
    <div class="mb-5">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>